<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-635BP1H" failures="1" tests="4" name="Personal Loan" time="0.093" errors="0" timestamp="2024-08-23T18:37:13 IST">
  <testcase classname="test.day3" name="APIHomeLoan" time="0.015"/>
  <testcase classname="test.day1" name="ThirdTest" time="0.029">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.ThirdTest(day1.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ThirdTest -->
  <testcase classname="test.day3" name="MobileHomeLoan" time="0.012"/>
  <testcase classname="test.day3" name="WebHomeLoan" time="0.003"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.day1" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal Loan -->
